"""add unique constraints to master data codes

Revision ID: 0eb66158ecc7
Revises: 90f58653a1a8
Create Date: 2026-03-06 10:00:30.240865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb66158ecc7'
down_revision: Union[str, None] = '90f58653a1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_customer_code', 'customers', ['entity_id', 'code'])
    op.create_unique_constraint('uq_department_code', 'departments', ['entity_id', 'code'])
    op.create_unique_constraint('uq_grade_code', 'grades', ['entity_id', 'code'])
    op.create_unique_constraint('uq_group_code', 'groups', ['entity_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_group_code', 'groups', type_='unique')
    op.drop_constraint('uq_grade_code', 'grades', type_='unique')
    op.drop_constraint('uq_department_code', 'departments', type_='unique')
    op.drop_constraint('uq_customer_code', 'customers', type_='unique')
    # ### end Alembic commands ###
