"""add_salary_component_category_and_payroll_breakdown

Revision ID: 13ed04a68d96
Revises: bb5108d1fcf4
Create Date: 2026-03-06 18:11:55.748559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13ed04a68d96'
down_revision: Union[str, None] = 'bb5108d1fcf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_records', sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('salary_structures', sa.Column('category', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary_structures', 'category')
    op.drop_column('payroll_records', 'breakdown')
    # ### end Alembic commands ###
