"""add claim_receipts table

Revision ID: 2c2a2e4a08e3
Revises: 83e32cecd290
Create Date: 2026-03-18 09:55:35.494965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2a2e4a08e3'
down_revision: Union[str, None] = '83e32cecd290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_receipts',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('receipt_url', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_receipts_claim_id'), 'claim_receipts', ['claim_id'], unique=False)
    op.drop_column('claim_requests', 'receipt_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_requests', sa.Column('receipt_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_claim_receipts_claim_id'), table_name='claim_receipts')
    op.drop_table('claim_receipts')
    # ### end Alembic commands ###
