"""add_ip_address_to_audit_logs

Revision ID: 2d18d61a17d4
Revises: 5e7965148e3d
Create Date: 2026-03-10 17:48:00.165045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d18d61a17d4'
down_revision: Union[str, None] = '5e7965148e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'ip_address')
    # ### end Alembic commands ###
