"""add offered ot and adjustments

Revision ID: 40cee829ed93
Revises: c8e87e0d3743
Create Date: 2026-03-04 00:23:50.486609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40cee829ed93'
down_revision: Union[str, None] = 'c8e87e0d3743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_attendance', sa.Column('ot_adjustment_1_5x', sa.Numeric(precision=5, scale=2), nullable=True))
    op.execute("UPDATE daily_attendance SET ot_adjustment_1_5x = 0")
    op.alter_column('daily_attendance', 'ot_adjustment_1_5x', nullable=False)

    op.add_column('daily_attendance', sa.Column('ot_adjustment_2x', sa.Numeric(precision=5, scale=2), nullable=True))
    op.execute("UPDATE daily_attendance SET ot_adjustment_2x = 0")
    op.alter_column('daily_attendance', 'ot_adjustment_2x', nullable=False)

    op.add_column('daily_attendance', sa.Column('adjustment_reason', sa.Text(), nullable=True))

    op.add_column('shifts', sa.Column('offered_ot_1_5x', sa.Numeric(precision=4, scale=2), nullable=True))
    op.execute("UPDATE shifts SET offered_ot_1_5x = 0")
    op.alter_column('shifts', 'offered_ot_1_5x', nullable=False)

    op.add_column('shifts', sa.Column('offered_ot_2_0x', sa.Numeric(precision=4, scale=2), nullable=True))
    op.execute("UPDATE shifts SET offered_ot_2_0x = 0")
    op.alter_column('shifts', 'offered_ot_2_0x', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'offered_ot_2_0x')
    op.drop_column('shifts', 'offered_ot_1_5x')
    op.drop_column('daily_attendance', 'adjustment_reason')
    op.drop_column('daily_attendance', 'ot_adjustment_2x')
    op.drop_column('daily_attendance', 'ot_adjustment_1_5x')
    # ### end Alembic commands ###
