"""add_attendance_roster_mode_and_calculation_log

Revision ID: 462f4e9b540a
Revises: dfc76306f105
Create Date: 2026-03-04 19:33:51.358103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462f4e9b540a'
down_revision: Union[str, None] = 'dfc76306f105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable first
    op.add_column('entities', sa.Column('attendance_roster_mode', sa.String(length=20), nullable=True))
    
    # 2. Update existing rows to 'manual'
    op.execute("UPDATE entities SET attendance_roster_mode = 'manual'")
    
    # 3. Set column to NOT NULL
    op.alter_column('entities', 'attendance_roster_mode', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'attendance_roster_mode')
    # ### end Alembic commands ###
