"""add is_expired to sdl_rate_config_v2

Revision ID: 52e8a34a8e80
Revises: 3acc2c9cef72
Create Date: 2026-03-07 16:47:12.538056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e8a34a8e80'
down_revision: Union[str, None] = '6e6ebe63bfb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sdl_rate_config', sa.Column('is_expired', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sdl_rate_config', 'is_expired')
    # ### end Alembic commands ###
