"""add emergency contact fields to person

Revision ID: 5affbbd63028
Revises: 0eb66158ecc7
Create Date: 2026-03-06 11:06:52.994889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5affbbd63028'
down_revision: Union[str, None] = '0eb66158ecc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('emergency_contact_name', sa.String(length=255), nullable=True))
    op.add_column('persons', sa.Column('emergency_contact_relationship', sa.String(length=100), nullable=True))
    op.add_column('persons', sa.Column('emergency_contact_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'emergency_contact_number')
    op.drop_column('persons', 'emergency_contact_relationship')
    op.drop_column('persons', 'emergency_contact_name')
    # ### end Alembic commands ###
