"""add_person_cpf_summary

Revision ID: 5e7965148e3d
Revises: 9174e90abbce
Create Date: 2026-03-07 18:49:30.390606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7965148e3d'
down_revision: Union[str, None] = '9174e90abbce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_cpf_summaries',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('ytd_ow', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ytd_aw', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ytd_cpf_ee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ytd_cpf_er', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('last_updated_period', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'year', name='uq_person_cpf_year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_cpf_summaries')
    # ### end Alembic commands ###
