"""add_unique_constraints_to_entity_fields

Revision ID: 6b3dbded6774
Revises: 7b453da9bf40
Create Date: 2026-03-06 23:35:43.037642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3dbded6774'
down_revision: Union[str, None] = '7b453da9bf40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'entities', ['cpf_account_no'])
    op.create_unique_constraint(None, 'entities', ['iras_tax_ref'])
    op.create_unique_constraint(None, 'entities', ['gst_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entities', type_='unique')
    op.drop_constraint(None, 'entities', type_='unique')
    op.drop_constraint(None, 'entities', type_='unique')
    # ### end Alembic commands ###
