"""add is_expired to shg_rate_config

Revision ID: 6e6ebe63bfb4
Revises: 897580ede0fb
Create Date: 2026-03-07 16:33:49.591907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6ebe63bfb4'
down_revision: Union[str, None] = '897580ede0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shg_rate_config', sa.Column('is_expired', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shg_rate_config', 'is_expired')
    # ### end Alembic commands ###
