"""separate grace periods for shifts

Revision ID: 8069a202c146
Revises: 0dedd41cee1e
Create Date: 2026-03-03 22:27:57.580994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8069a202c146'
down_revision: Union[str, None] = '0dedd41cee1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('lateness_grace_minutes', sa.Integer(), nullable=True))
    op.execute("UPDATE shifts SET lateness_grace_minutes = grace_minutes")
    op.alter_column('shifts', 'lateness_grace_minutes', nullable=False)

    op.add_column('shifts', sa.Column('early_exit_grace_minutes', sa.Integer(), nullable=True))
    op.execute("UPDATE shifts SET early_exit_grace_minutes = 0")
    op.alter_column('shifts', 'early_exit_grace_minutes', nullable=False)

    op.drop_column('shifts', 'grace_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('grace_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('shifts', 'early_exit_grace_minutes')
    op.drop_column('shifts', 'lateness_grace_minutes')
    # ### end Alembic commands ###
