"""add claims module tables

Revision ID: 83e32cecd290
Revises: ce53f47b2361
Create Date: 2026-03-18 00:07:00.699562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83e32cecd290'
down_revision: Union[str, None] = 'ce53f47b2361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_categories',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_categories_entity_id'), 'claim_categories', ['entity_id'], unique=False)
    op.create_index(op.f('ix_claim_categories_tenant_id'), 'claim_categories', ['tenant_id'], unique=False)
    op.create_table('claim_requests',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employment_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('receipt_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payroll_run_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['claim_categories.id'], ),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_requests_employment_id'), 'claim_requests', ['employment_id'], unique=False)
    op.create_index(op.f('ix_claim_requests_tenant_id'), 'claim_requests', ['tenant_id'], unique=False)
    op.drop_table('claim_applications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_applications',
    sa.Column('employment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('claim_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('paid_in_period', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='claim_applications_approved_by_fkey'),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], name='claim_applications_employment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='claim_applications_pkey')
    )
    op.drop_index(op.f('ix_claim_requests_tenant_id'), table_name='claim_requests')
    op.drop_index(op.f('ix_claim_requests_employment_id'), table_name='claim_requests')
    op.drop_table('claim_requests')
    op.drop_index(op.f('ix_claim_categories_tenant_id'), table_name='claim_categories')
    op.drop_index(op.f('ix_claim_categories_entity_id'), table_name='claim_categories')
    op.drop_table('claim_categories')
    # ### end Alembic commands ###
