"""add is_expired to cpf_rate_config

Revision ID: 897580ede0fb
Revises: a712987a4c3d
Create Date: 2026-03-07 15:53:13.757784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897580ede0fb'
down_revision: Union[str, None] = 'a712987a4c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cpf_rate_config', sa.Column('is_expired', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cpf_rate_config', 'is_expired')
    # ### end Alembic commands ###
