"""Add user_id to system_audit_logs

Revision ID: 900c08ec7e01
Revises: 2d18d61a17d4
Create Date: 2026-03-10 22:20:49.028803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '900c08ec7e01'
down_revision: Union[str, None] = '2d18d61a17d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_audit_logs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'system_audit_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_audit_logs', type_='foreignkey')
    op.drop_column('system_audit_logs', 'user_id')
    # ### end Alembic commands ###
