"""Add child_order to LeaveRequest

Revision ID: 90f58653a1a8
Revises: 6e418a6b84c3
Create Date: 2026-03-05 14:21:03.181304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f58653a1a8'
down_revision: Union[str, None] = '6e418a6b84c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('child_order', sa.Integer(), nullable=True))
    op.drop_constraint('uq_leave_type_policy', 'leave_type_policies', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_leave_type_policy', 'leave_type_policies', ['entity_id', 'leave_type_code', 'effective_from'])
    op.drop_column('leave_requests', 'child_order')
    # ### end Alembic commands ###
