"""add_granular_cpf_to_payroll_record

Revision ID: 9174e90abbce
Revises: faf1414e7477
Create Date: 2026-03-07 17:57:14.288893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9174e90abbce'
down_revision: Union[str, None] = 'faf1414e7477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_records', sa.Column('cpf_oa', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=False))
    op.add_column('payroll_records', sa.Column('cpf_sa', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=False))
    op.add_column('payroll_records', sa.Column('cpf_ma', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_records', 'cpf_ma')
    op.drop_column('payroll_records', 'cpf_sa')
    op.drop_column('payroll_records', 'cpf_oa')
    # ### end Alembic commands ###
