"""add_ket_fields_and_snapshot_model_v2

Revision ID: 9be2d8b67f31
Revises: 13ed04a68d96
Create Date: 2026-03-06 19:11:29.970756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9be2d8b67f31'
down_revision: Union[str, None] = '13ed04a68d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_employment_terms',
    sa.Column('employment_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('terms_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_by_employee_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employment_id'], ['employments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employments', sa.Column('ot_rate', sa.Numeric(precision=3, scale=2), server_default='1.5', nullable=False))
    op.add_column('employments', sa.Column('salary_period', sa.String(length=20), server_default='monthly', nullable=False))
    op.add_column('employments', sa.Column('ot_payment_period', sa.String(length=20), server_default='monthly', nullable=False))
    op.add_column('employments', sa.Column('job_responsibilities', sa.Text(), nullable=True))
    op.add_column('employments', sa.Column('probation_period', sa.String(length=50), nullable=True))
    op.add_column('employments', sa.Column('notice_period', sa.String(length=50), nullable=True))
    op.add_column('employments', sa.Column('work_location', sa.Text(), nullable=True))
    op.add_column('employments', sa.Column('medical_benefits', sa.Text(), nullable=True))
    op.add_column('employments', sa.Column('dental_benefits', sa.Text(), nullable=True))
    op.add_column('employments', sa.Column('insurance_benefits', sa.Text(), nullable=True))
    op.add_column('employments', sa.Column('other_benefits', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employments', 'other_benefits')
    op.drop_column('employments', 'insurance_benefits')
    op.drop_column('employments', 'dental_benefits')
    op.drop_column('employments', 'medical_benefits')
    op.drop_column('employments', 'work_location')
    op.drop_column('employments', 'notice_period')
    op.drop_column('employments', 'probation_period')
    op.drop_column('employments', 'job_responsibilities')
    op.drop_column('employments', 'ot_payment_period')
    op.drop_column('employments', 'salary_period')
    op.drop_column('employments', 'ot_rate')
    op.drop_table('key_employment_terms')
    # ### end Alembic commands ###
