"""add_website_banking_logo_to_entity

Revision ID: a712987a4c3d
Revises: f5395783ef8c
Create Date: 2026-03-07 00:36:25.902405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a712987a4c3d'
down_revision: Union[str, None] = 'f5395783ef8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('entities', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('entities', sa.Column('bank_account_no', sa.String(length=100), nullable=True))
    op.add_column('entities', sa.Column('bank_account_name', sa.String(length=255), nullable=True))
    op.add_column('entities', sa.Column('bank_branch_code', sa.String(length=20), nullable=True))
    op.add_column('entities', sa.Column('bank_swift_code', sa.String(length=20), nullable=True))
    op.add_column('entities', sa.Column('logo_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'logo_url')
    op.drop_column('entities', 'bank_swift_code')
    op.drop_column('entities', 'bank_branch_code')
    op.drop_column('entities', 'bank_account_name')
    op.drop_column('entities', 'bank_account_no')
    op.drop_column('entities', 'bank_name')
    op.drop_column('entities', 'website')
    # ### end Alembic commands ###
