"""add penalty rounding blocks to shifts

Revision ID: c8e87e0d3743
Revises: 8069a202c146
Create Date: 2026-03-03 22:46:09.416493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e87e0d3743'
down_revision: Union[str, None] = '8069a202c146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('late_penalty_rounding_block', sa.Integer(), nullable=True))
    op.execute("UPDATE shifts SET late_penalty_rounding_block = 0")
    op.alter_column('shifts', 'late_penalty_rounding_block', nullable=False)

    op.add_column('shifts', sa.Column('early_penalty_rounding_block', sa.Integer(), nullable=True))
    op.execute("UPDATE shifts SET early_penalty_rounding_block = 0")
    op.alter_column('shifts', 'early_penalty_rounding_block', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'early_penalty_rounding_block')
    op.drop_column('shifts', 'late_penalty_rounding_block')
    # ### end Alembic commands ###
