"""add avatar_url to users

Revision ID: ce53f47b2361
Revises: 900c08ec7e01
Create Date: 2026-03-15 15:46:05.851900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce53f47b2361'
down_revision: Union[str, None] = '900c08ec7e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_runs', sa.Column('group_ids', sa.ARRAY(sa.UUID()), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('payroll_runs', 'group_ids')
    # ### end Alembic commands ###
