"""add_person_id_to_users

Revision ID: dfc76306f105
Revises: be145a03f357
Create Date: 2026-03-04 13:47:52.099000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc76306f105'
down_revision: Union[str, None] = 'be145a03f357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('person_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'persons', ['person_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'person_id')
    # ### end Alembic commands ###
