"""add_foreign_worker_levy

Revision ID: ed44efe77105
Revises: 5affbbd63028
Create Date: 2026-03-06 12:45:55.964331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed44efe77105'
down_revision: Union[str, None] = '5affbbd63028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employments', sa.Column('foreign_worker_levy', sa.Numeric(precision=12, scale=2), nullable=True))
    op.execute('UPDATE employments SET foreign_worker_levy = 0.0')
    op.alter_column('employments', 'foreign_worker_levy', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employments', 'foreign_worker_levy')
    # ### end Alembic commands ###
