"""remove_unique_constraint_gst_no

Revision ID: f5395783ef8c
Revises: 6b3dbded6774
Create Date: 2026-03-06 23:38:11.643024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5395783ef8c'
down_revision: Union[str, None] = '6b3dbded6774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('entities_gst_no_key', 'entities', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('entities_gst_no_key', 'entities', ['gst_no'])
    # ### end Alembic commands ###
