"""add_cpf_allocation_config

Revision ID: faf1414e7477
Revises: 52e8a34a8e80
Create Date: 2026-03-07 17:54:47.760235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf1414e7477'
down_revision: Union[str, None] = '52e8a34a8e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpf_allocation_config',
    sa.Column('age_from', sa.Integer(), nullable=False),
    sa.Column('age_to', sa.Integer(), nullable=False),
    sa.Column('oa_ratio', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('sa_ratio', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('ma_ratio', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cpf_allocation_config')
    # ### end Alembic commands ###
